#pragma config(Sensor, S1,     lightSensorRight, sensorLightInactive)
#pragma config(Sensor, S4,     lightSensorLeft, sensorLightInactive)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task DriveLeft(){
 while(true){
   motor[motorC]= SensorValue(lightSensorLeft);
 }
}

task DriveRight(){
 while(true){
    motor[motorB]= SensorValue(lightSensorRight);
 }
}

task main()
{
	while(true){
 		StartTask(DriveLeft);
 		StartTask(DriveRight);
	}
}
