#pragma config(Sensor, S1,     touchSensor,              sensorTouch)
#pragma config(Sensor, S3,     compassSensor,            sensorVirtualCompass)
#pragma config(Sensor, S2,     lightSensor,              sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,              sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// This is for the NXT model, not TETRIX

/************************************\
|*  ROBOTC Virtual World            *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/


task line(){
	while(true){
		if(SensorValue(lightSensor) < 50){
		motor[motorC] = 0;
  		motor[motorB] = 0;
		//wait1Msec(50);

		motor[motorC] = 0;
  		motor[motorB] = 27;

		}
	}
}

task main(){
		StartTask(line);
	while(true){
		if(SensorValue(lightSensor) => 50){
		motor[motorC] = 0;
  		motor[motorB] = 0;
		//	wait1Msec(50);

		motor[motorC] = 27;
  		motor[motorB] = 0;
  		}
	}
}
