#pragma config(Sensor, S1,     touchSensor,              sensorTouch)
#pragma config(Sensor, S2,     compassSensor,            sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,              sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,              sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// This is for the NXT model, not TETRIX

/************************************\
|*  ROBOTC Virtual World            *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

task main()
{
	//avanza 4 segundos
	motor[motorC]=100;
	motor[motorB]=100;
	wait1Msec(4000);
	//se espera 1 segundo
	motor[motorC]=0;
	motor[motorB]=0;
	wait1Msec(1000);

	//gira a la izquierda
	motor[motorB]=100;
	wait1Msec(1000);
	//se espera 1 segundo
	motor[motorC]=0;
	motor[motorB]=0;
	wait1Msec(1000);
	//avanza 3,5egundos
	motor[motorC]=100;
	motor[motorB]=100;
	wait1Msec(3500);
	//se espera 1 segundo
	motor[motorC]=0;
	motor[motorB]=0;
	wait1Msec(1000);
	//gira a la derecha
	motor[motorC]=100;
	wait1Msec(1000);
	//se espera 1 segundo
	motor[motorC]=0;
	motor[motorB]=0;
	wait1Msec(1000);
	//avanza 2 segundo
	motor[motorC]=100;
	motor[motorB]=100;
	wait1Msec(2000);
	//se espera 1 segundo
	motor[motorC]=0;
	motor[motorB]=0;
	wait1Msec(1000);
	//gira a la derecha
	motor[motorC]=100;
	wait1Msec(1000);
	//se espera 1 segundo
	motor[motorC]=0;
	motor[motorB]=0;
	wait1Msec(1000);
	//avanza 2 segundo
	motor[motorC]=100;
	motor[motorB]=100;
	wait1Msec(2000);
}
