#pragma config(Sensor, S1,     touchSensor,              sensorTouch)
#pragma config(Sensor, S2,     compassSensor,            sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,              sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,              sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// This is for the NXT model, not TETRIX

/************************************\
|*  ROBOTC Virtual World            *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

task main()
{
	motor[motorC] = 50;
 	motor[motorB] = 50;
 	wait1Msec(2000);
 	motor[motorB] = -50;
	wait1Msec(2000 + random(3000));
 	motor[motorC] = 0;
 	motor[motorB] = 0;

	while(true){
  	while(SensorValue(sonarSensor) < 0){
     	motor[motorC] = 0;
     	motor[motorB] = 50;

  		if(SensorValue(lightSensor) < 40){

  			motor[motorC] = -75;
     		motor[motorB] = -75;
  			wait1Msec(1500);
   			int valor = random(2);
  			if(valor == 1){
  				motor[motorC] = 0;
     			motor[motorB] = 75;
     			wait1Msec(3000);
    		}else{
    			motor[motorC] = 75;
     			motor[motorB] = 0;
     			wait1Msec(3000);
     		}//fin else
  		}//fin if light
    } //fin while
    while(SensorValue(sonarSensor) > 0){
     	motor[motorC] = 100;
     	motor[motorB] = 100;

    	if(SensorValue(lightSensor) < 40){

  			motor[motorC] = -75;
     		motor[motorB] = -75;
  			wait1Msec(1500);
   			int valor = random(2);
  			if(valor == 1){
  				motor[motorC] = 0;
     			motor[motorB] = 75;
     			wait1Msec(3000);
    		}else{
    			motor[motorC] = 75;
     			motor[motorB] = 0;
     			wait1Msec(3000);
     		}//fin else
  		}//fin if light
  	 } //fin while
  }
}
